server:
  port: 8000
  undertow:
    buffer-size: 1024
    direct-buffers: true
    threads:
      worker: 20
      io: 4

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: on
  resources:
    static-locations: /online_judge_data/static/
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/vjudge?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456789
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password: 123456789
    database: 0
    timeout: 1000


  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      location: /online_judge_data/tmp/

config_file:
  account: remote_account.json
  language: language_config.json
